#!/usr/bin/env zsh

autoload -Uz vcs_info

source "${SCRIPT_DIR}/prompt_j2_helpers"

# Provide relevant vcs info to the prompt


start_message() {
  print -P "$1"
}

change_exists() {
  if [[ `git status --porcelain` ]]; then
    return 0;
  else
    return 1;
  fi
}

init_vcs(){
  zstyle ':vcs_info:*' enable git
  zstyle ':vcs_info:*' check-for-changes true
  zstyle ':vcs_info:*' unstagedstr "$(color ! red)"
  zstyle ':vcs_info:*' stagedstr "$(color + green)"
  zstyle ':vcs_info:git:*' formats '%b%u%c'
}

LEFT='';
RIGHT='';

# echos a decorated vcs string
compose_vcs() {


  if (change_exists); then
    local decorated="$(color $LEFT red)${vcs_info_msg_0_}$(color $RIGHT red)"
  else
    local decorated="${LEFT}${vcs_info_msg_0_}${RIGHT}"
  fi

  print -Pn $decorated
}

run_vcs() {
  vcs_info

  if [[ (! -n $1) || (! -n $2)]]; then
    print "please provide prompt_j2_vcs with the required args"
    exit 1
  fi

  LEFT=$1   # delimiter for left of vcs string
  RIGHT=$2  # delimiter for right of vcs string

  print -Pn  "$(compose_vcs)"
}

init_vcs
run_vcs $1 $2

