#!/usr/bin/env zsh

autoload -U colors && colors

# Various helper functions for the prompt

color(){
  print -Pn "%{$fg[${2}]%}${1}%{$reset_color%}"
}

get_time() { 
  print -Pn '[%D{%L:%M:%S %p}]'
}

show_cursor(){
  print -Pn "\e[?25h"
}

hide_cursor(){
  print -Pn "\e[?25l"
}

